name: Deploy On Server

on:
  push:
    branches: [main]

jobs:
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Install Dependecies
        run: |
          echo "Running Installing Dependecies..."
          npm install
      - name: Run Linting
        run: |
          echo "Running Linting Tests"
          npm run lint
        env:
          CI: true
  deploy:
    name: Deoply On Host
    runs-on: ubuntu-latest
    needs: [lintTest]
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            echo "start Deploying"
            cd mana/mana-front
            npm -v
